# Generated by Django 4.0.3 on 2022-04-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_name', models.CharField(max_length=100)),
                ('away_team_name', models.CharField(max_length=100)),
                ('home_team_goals', models.IntegerField()),
                ('away_team_goals', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('arena', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0, help_text='The field stores the score of each member.')),
                ('victory', models.IntegerField(default=0, help_text='The field stores the number of times the score was hit.')),
            ],
        ),
        migrations.CreateModel(
            name='Hunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_hunch', models.IntegerField(null=True)),
                ('away_team_hunch', models.IntegerField(null=True)),
                ('point', models.IntegerField(default=0)),
                ('match_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='predict_game.match')),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='predict_game.member')),
            ],
        ),
    ]
