# Generated by Django 4.0.3 on 2022-04-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunch',
            name='point',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='score',
            field=models.IntegerField(default=0, editable=False, help_text='The field stores the score of each member.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='victory',
            field=models.IntegerField(default=0, editable=False, help_text='The field stores the number of times the score was hit.'),
        ),
    ]
