# Generated by Django 4.0.3 on 2022-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_game', '0002_alter_hunch_point_alter_member_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunch',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
